/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JPanel;

/**
 *
 * @author Thuy SCTV
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        showPanel(new QuanLyBanHangJpanel());
    }

    private void showPanel(JPanel panel) {
        mainPanel.removeAll();
        mainPanel.add(panel);
        mainPanel.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelBanHang = new javax.swing.JPanel();
        labelBanHang = new javax.swing.JLabel();
        panelHoaDon = new javax.swing.JPanel();
        labelHoaDon = new javax.swing.JLabel();
        panelSanPham = new javax.swing.JPanel();
        labelSanPham = new javax.swing.JLabel();
        panelKhuyenMai = new javax.swing.JPanel();
        labelKhuyenMai = new javax.swing.JLabel();
        panelThongKe = new javax.swing.JPanel();
        labelThongKe = new javax.swing.JLabel();
        panelNhanVien = new javax.swing.JPanel();
        labelNhanVien = new javax.swing.JLabel();
        panelDoiMatKhau = new javax.swing.JPanel();
        labelDoiMatKhau = new javax.swing.JLabel();
        panelDangXuat = new javax.swing.JPanel();
        labelDangXuat = new javax.swing.JLabel();
        PanelDanhMuc = new javax.swing.JPanel();
        labelDanhMuc = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1800, 1000));
        setSize(new java.awt.Dimension(0, 0));

        MenuPanel.setBackground(new java.awt.Color(246, 225, 225));
        MenuPanel.setMaximumSize(new java.awt.Dimension(300, 1000));
        MenuPanel.setMinimumSize(new java.awt.Dimension(300, 1000));
        MenuPanel.setName(""); // NOI18N
        MenuPanel.setPreferredSize(new java.awt.Dimension(300, 1000));
        MenuPanel.setRequestFocusEnabled(false);
        MenuPanel.setVerifyInputWhenFocusTarget(false);

        jPanel3.setBackground(new java.awt.Color(246, 225, 225));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(128, 0, 0));
        jLabel2.setText("HB160");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(128, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        panelBanHang.setBackground(new java.awt.Color(246, 225, 225));
        panelBanHang.setPreferredSize(new java.awt.Dimension(300, 118));
        panelBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBanHangMouseEntered(evt);
            }
        });

        labelBanHang.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        labelBanHang.setForeground(new java.awt.Color(128, 0, 0));
        labelBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-cart-48.png"))); // NOI18N
        labelBanHang.setText("  Bán Hàng");
        labelBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBanHangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBanHangLayout = new javax.swing.GroupLayout(panelBanHang);
        panelBanHang.setLayout(panelBanHangLayout);
        panelBanHangLayout.setHorizontalGroup(
            panelBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBanHangLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelBanHang)
                .addGap(50, 50, 50))
        );
        panelBanHangLayout.setVerticalGroup(
            panelBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBanHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelBanHang)
                .addGap(35, 35, 35))
        );

        panelHoaDon.setBackground(new java.awt.Color(246, 225, 225));
        panelHoaDon.setPreferredSize(new java.awt.Dimension(300, 75));
        panelHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHoaDonMouseEntered(evt);
            }
        });

        labelHoaDon.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        labelHoaDon.setForeground(new java.awt.Color(128, 0, 0));
        labelHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/document-2-48.png"))); // NOI18N
        labelHoaDon.setText("  Hoá Đơn");
        labelHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHoaDonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelHoaDonLayout = new javax.swing.GroupLayout(panelHoaDon);
        panelHoaDon.setLayout(panelHoaDonLayout);
        panelHoaDonLayout.setHorizontalGroup(
            panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHoaDonLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelHoaDon)
                .addGap(50, 50, 50))
        );
        panelHoaDonLayout.setVerticalGroup(
            panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHoaDonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelHoaDon)
                .addGap(35, 35, 35))
        );

        panelSanPham.setBackground(new java.awt.Color(246, 225, 225));
        panelSanPham.setPreferredSize(new java.awt.Dimension(300, 75));
        panelSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSanPhamMouseEntered(evt);
            }
        });

        labelSanPham.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        labelSanPham.setForeground(new java.awt.Color(128, 0, 0));
        labelSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/product-48.png"))); // NOI18N
        labelSanPham.setText("  Sản Phẩm");
        labelSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSanPhamMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSanPhamLayout = new javax.swing.GroupLayout(panelSanPham);
        panelSanPham.setLayout(panelSanPhamLayout);
        panelSanPhamLayout.setHorizontalGroup(
            panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSanPhamLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelSanPham)
                .addGap(32, 32, 32))
        );
        panelSanPhamLayout.setVerticalGroup(
            panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSanPhamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelSanPham)
                .addGap(47, 47, 47))
        );

        panelKhuyenMai.setBackground(new java.awt.Color(246, 225, 225));
        panelKhuyenMai.setPreferredSize(new java.awt.Dimension(300, 75));
        panelKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelKhuyenMaiMouseEntered(evt);
            }
        });

        labelKhuyenMai.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        labelKhuyenMai.setForeground(new java.awt.Color(128, 0, 0));
        labelKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sale-48.png"))); // NOI18N
        labelKhuyenMai.setText("  Khuyến Mại");
        labelKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKhuyenMaiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelKhuyenMaiLayout = new javax.swing.GroupLayout(panelKhuyenMai);
        panelKhuyenMai.setLayout(panelKhuyenMaiLayout);
        panelKhuyenMaiLayout.setHorizontalGroup(
            panelKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKhuyenMaiLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelKhuyenMai)
                .addGap(17, 17, 17))
        );
        panelKhuyenMaiLayout.setVerticalGroup(
            panelKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKhuyenMaiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelKhuyenMai)
                .addGap(35, 35, 35))
        );

        panelThongKe.setBackground(new java.awt.Color(246, 225, 225));
        panelThongKe.setPreferredSize(new java.awt.Dimension(300, 75));
        panelThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelThongKeMouseEntered(evt);
            }
        });

        labelThongKe.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        labelThongKe.setForeground(new java.awt.Color(128, 0, 0));
        labelThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/statistics-48.png"))); // NOI18N
        labelThongKe.setText("  Thống Kê");
        labelThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelThongKeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelThongKeLayout = new javax.swing.GroupLayout(panelThongKe);
        panelThongKe.setLayout(panelThongKeLayout);
        panelThongKeLayout.setHorizontalGroup(
            panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongKeLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelThongKe)
                .addGap(44, 44, 44))
        );
        panelThongKeLayout.setVerticalGroup(
            panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongKeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelThongKe)
                .addGap(35, 35, 35))
        );

        panelNhanVien.setBackground(new java.awt.Color(246, 225, 225));
        panelNhanVien.setPreferredSize(new java.awt.Dimension(300, 75));
        panelNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelNhanVienMouseEntered(evt);
            }
        });

        labelNhanVien.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        labelNhanVien.setForeground(new java.awt.Color(128, 0, 0));
        labelNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user-48.png"))); // NOI18N
        labelNhanVien.setText("  Nhân Viên");
        labelNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelNhanVienMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelNhanVienLayout = new javax.swing.GroupLayout(panelNhanVien);
        panelNhanVien.setLayout(panelNhanVienLayout);
        panelNhanVienLayout.setHorizontalGroup(
            panelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNhanVienLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelNhanVien)
                .addGap(35, 35, 35))
        );
        panelNhanVienLayout.setVerticalGroup(
            panelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNhanVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNhanVien)
                .addGap(35, 35, 35))
        );

        panelDoiMatKhau.setBackground(new java.awt.Color(246, 225, 225));
        panelDoiMatKhau.setPreferredSize(new java.awt.Dimension(300, 75));
        panelDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDoiMatKhauMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDoiMatKhauMouseEntered(evt);
            }
        });

        labelDoiMatKhau.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        labelDoiMatKhau.setForeground(new java.awt.Color(128, 0, 0));
        labelDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/padlock-48.png"))); // NOI18N
        labelDoiMatKhau.setText("  Đổi Mật khẩu");
        labelDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDoiMatKhauMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelDoiMatKhauLayout = new javax.swing.GroupLayout(panelDoiMatKhau);
        panelDoiMatKhau.setLayout(panelDoiMatKhauLayout);
        panelDoiMatKhauLayout.setHorizontalGroup(
            panelDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDoiMatKhauLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelDoiMatKhau)
                .addGap(35, 35, 35))
        );
        panelDoiMatKhauLayout.setVerticalGroup(
            panelDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDoiMatKhauLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDoiMatKhau)
                .addGap(35, 35, 35))
        );

        panelDangXuat.setBackground(new java.awt.Color(246, 225, 225));
        panelDangXuat.setPreferredSize(new java.awt.Dimension(300, 75));

        labelDangXuat.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        labelDangXuat.setForeground(new java.awt.Color(128, 0, 0));
        labelDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/door-5-48.png"))); // NOI18N
        labelDangXuat.setText("  Đăng Xuất");

        javax.swing.GroupLayout panelDangXuatLayout = new javax.swing.GroupLayout(panelDangXuat);
        panelDangXuat.setLayout(panelDangXuatLayout);
        panelDangXuatLayout.setHorizontalGroup(
            panelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDangXuatLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelDangXuat)
                .addGap(65, 65, 65))
        );
        panelDangXuatLayout.setVerticalGroup(
            panelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDangXuatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDangXuat)
                .addGap(35, 35, 35))
        );

        PanelDanhMuc.setBackground(new java.awt.Color(246, 225, 225));
        PanelDanhMuc.setPreferredSize(new java.awt.Dimension(300, 75));
        PanelDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelDanhMucMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelDanhMucMouseEntered(evt);
            }
        });

        labelDanhMuc.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        labelDanhMuc.setForeground(new java.awt.Color(128, 0, 0));
        labelDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/t-shirt-48.png"))); // NOI18N
        labelDanhMuc.setText("  Danh Mục");
        labelDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDanhMucMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelDanhMucLayout = new javax.swing.GroupLayout(PanelDanhMuc);
        PanelDanhMuc.setLayout(PanelDanhMucLayout);
        PanelDanhMucLayout.setHorizontalGroup(
            PanelDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDanhMucLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelDanhMuc)
                .addGap(50, 50, 50))
        );
        PanelDanhMucLayout.setVerticalGroup(
            PanelDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDanhMucLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDanhMuc)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBanHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(PanelDanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(panelBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(panelSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(panelDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(246, 225, 225));
        mainPanel.setMaximumSize(new java.awt.Dimension(1500, 1000));
        mainPanel.setMinimumSize(new java.awt.Dimension(1500, 1000));
        mainPanel.setName(""); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(1500, 1000));
        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBanHangMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_panelBanHangMouseEntered

    private void panelHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHoaDonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelHoaDonMouseEntered

    private void panelSanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSanPhamMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelSanPhamMouseEntered

    private void panelKhuyenMaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelKhuyenMaiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelKhuyenMaiMouseEntered

    private void panelThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelThongKeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelThongKeMouseEntered

    private void panelNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNhanVienMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelNhanVienMouseEntered

    private void panelDoiMatKhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDoiMatKhauMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelDoiMatKhauMouseEntered

    private void PanelDanhMucMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDanhMucMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PanelDanhMucMouseEntered

    private void panelNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNhanVienMouseClicked
        // TODO add your handling code here:
        showPanel(new QuanLyNhanVienJPanel());
    }//GEN-LAST:event_panelNhanVienMouseClicked

    private void labelNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNhanVienMouseClicked
        // TODO add your handling code here:
        showPanel(new QuanLyNhanVienJPanel());
    }//GEN-LAST:event_labelNhanVienMouseClicked

    private void panelHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHoaDonMouseClicked
        // TODO add your handling code here:
        showPanel(new QuanLyHoaDonJpanel());
    }//GEN-LAST:event_panelHoaDonMouseClicked

    private void labelHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHoaDonMouseClicked
        // TODO add your handling code here:
        showPanel(new QuanLyHoaDonJpanel());
    }//GEN-LAST:event_labelHoaDonMouseClicked

    private void labelDanhMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDanhMucMouseClicked
        // TODO add your handling code here:
        showPanel(new QuanLyDanhMucJpanel());
    }//GEN-LAST:event_labelDanhMucMouseClicked

    private void labelKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKhuyenMaiMouseClicked
        // TODO add your handling code here:
        showPanel(new QuanLyKhuyenMaiJpanel());
    }//GEN-LAST:event_labelKhuyenMaiMouseClicked

    private void panelBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBanHangMouseClicked
        // TODO add your handling code here:
        showPanel(new QuanLyBanHangJpanel());
    }//GEN-LAST:event_panelBanHangMouseClicked

    private void labelBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBanHangMouseClicked
        // TODO add your handling code here:
        showPanel(new QuanLyBanHangJpanel());
    }//GEN-LAST:event_labelBanHangMouseClicked

    private void panelSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSanPhamMouseClicked
        // TODO add your handling code here:
        showPanel(new QuanLySanPhamJpanel());
    }//GEN-LAST:event_panelSanPhamMouseClicked

    private void labelSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSanPhamMouseClicked
        // TODO add your handling code here:
        showPanel(new QuanLySanPhamJpanel());
    }//GEN-LAST:event_labelSanPhamMouseClicked

    private void panelThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelThongKeMouseClicked
        // TODO add your handling code here:
        showPanel(new QuanLyThongKeJpanel());
    }//GEN-LAST:event_panelThongKeMouseClicked

    private void labelThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelThongKeMouseClicked
        // TODO add your handling code here:
        showPanel(new QuanLyThongKeJpanel());
    }//GEN-LAST:event_labelThongKeMouseClicked

    private void labelDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDoiMatKhauMouseClicked
        // TODO add your handling code here:
        showPanel(new DoiMatKhauJpanel());
    }//GEN-LAST:event_labelDoiMatKhauMouseClicked

    private void panelDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDoiMatKhauMouseClicked
        // TODO add your handling code here:
        showPanel(new DoiMatKhauJpanel());
    }//GEN-LAST:event_panelDoiMatKhauMouseClicked

    private void PanelDanhMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDanhMucMouseClicked
        // TODO add your handling code here:
        showPanel(new QuanLyDanhMucJpanel());
    }//GEN-LAST:event_PanelDanhMucMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel PanelDanhMuc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelBanHang;
    private javax.swing.JLabel labelDangXuat;
    private javax.swing.JLabel labelDanhMuc;
    private javax.swing.JLabel labelDoiMatKhau;
    private javax.swing.JLabel labelHoaDon;
    private javax.swing.JLabel labelKhuyenMai;
    private javax.swing.JLabel labelNhanVien;
    private javax.swing.JLabel labelSanPham;
    private javax.swing.JLabel labelThongKe;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelBanHang;
    private javax.swing.JPanel panelDangXuat;
    private javax.swing.JPanel panelDoiMatKhau;
    private javax.swing.JPanel panelHoaDon;
    private javax.swing.JPanel panelKhuyenMai;
    private javax.swing.JPanel panelNhanVien;
    private javax.swing.JPanel panelSanPham;
    private javax.swing.JPanel panelThongKe;
    // End of variables declaration//GEN-END:variables
}
