/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DanhMucDAO;
import enity.DanhMuc;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admim
 */
public class QuanLyDanhMucJpanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyDanhMucJpanel
     */
    public QuanLyDanhMucJpanel() {
        initComponents();
        fillTable();
    }

    private void fillTable() {
        DanhMucDAO danhMucDAO = new DanhMucDAO();
        List<DanhMuc> danhMucLst = danhMucDAO.readDanhMuc();

        DefaultTableModel model = (DefaultTableModel) tblDanhMuc.getModel();
        model.setRowCount(0);

        for (DanhMuc danhMuc : danhMucLst) {
            System.out.println("Adding product: " + danhMuc.getTenDM());

            Object[] rowdata = {
                danhMuc.getID(),
                danhMuc.getTenDM()
            };
            model.addRow(rowdata);
        }
    }

    private boolean showPasswordDialog() {
        java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        DoiMatKhauJdialog dialog = new DoiMatKhauJdialog(parentFrame, true);
        dialog.setLocationRelativeTo(this); // Center relative to the JPanel
        dialog.setVisible(true);
        return dialog.isAuthenticated();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtTenDanhMuc = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhMuc = new rojerusan.RSTableMetro();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1500, 1000));
        setMinimumSize(new java.awt.Dimension(1500, 1000));
        setPreferredSize(new java.awt.Dimension(1500, 1000));

        jPanel3.setBackground(new java.awt.Color(246, 225, 225));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(128, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(1300, 400));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(128, 0, 0));
        jLabel14.setText("Tên Danh Mục:");

        txtTenDanhMuc.setBackground(new java.awt.Color(246, 225, 225));
        txtTenDanhMuc.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtTenDanhMuc.setForeground(new java.awt.Color(128, 0, 0));
        txtTenDanhMuc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(128, 0, 0)));
        txtTenDanhMuc.setMinimumSize(new java.awt.Dimension(300, 30));
        txtTenDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDanhMucActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnThem.setForeground(new java.awt.Color(128, 0, 0));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-user-3-48.png"))); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(128, 0, 0)));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 255, 255));
        btnSua.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnSua.setForeground(new java.awt.Color(128, 0, 0));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/available-updates-48.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(128, 0, 0)));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(128, 0, 0));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete-48.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(128, 0, 0)));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTenDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(128, 0, 0));
        jLabel2.setText("Điều Chỉnh Thông Tin Danh Mục");

        jPanel4.setBackground(new java.awt.Color(246, 225, 225));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(128, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(1300, 400));

        tblDanhMuc.setBackground(new java.awt.Color(246, 225, 225));
        tblDanhMuc.setForeground(new java.awt.Color(255, 255, 255));
        tblDanhMuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Danh Mục", "Tên Danh Mục"
            }
        ));
        tblDanhMuc.setColorBackgoundHead(new java.awt.Color(128, 0, 0));
        tblDanhMuc.setColorBordeFilas(new java.awt.Color(128, 0, 0));
        tblDanhMuc.setColorBordeHead(new java.awt.Color(246, 225, 225));
        tblDanhMuc.setColorFilasBackgound1(new java.awt.Color(246, 225, 225));
        tblDanhMuc.setColorFilasBackgound2(new java.awt.Color(246, 225, 225));
        tblDanhMuc.setColorFilasForeground1(new java.awt.Color(128, 0, 0));
        tblDanhMuc.setColorFilasForeground2(new java.awt.Color(128, 0, 0));
        tblDanhMuc.setColorForegroundHead(new java.awt.Color(246, 225, 225));
        tblDanhMuc.setColorSelBackgound(new java.awt.Color(128, 0, 0));
        tblDanhMuc.setColorSelForeground(new java.awt.Color(246, 225, 225));
        tblDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhMucMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhMuc);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1286, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(128, 0, 0));
        jLabel3.setText("Thông Tin Danh Mục");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1284, Short.MAX_VALUE)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1296, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDanhMucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDanhMucActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String TenDanhMuc = txtTenDanhMuc.getText();

        if (TenDanhMuc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không Được Để Trống Tên", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DanhMucDAO danhMucDao = new DanhMucDAO();
        DanhMuc danhMuc = new DanhMuc(0, TenDanhMuc);
        int ketQua = danhMucDao.ThemDanhMuc(danhMuc);

        if (ketQua == 1) {
            JOptionPane.showMessageDialog(this, "Thêm Danh Mục Thành Công");
            txtTenDanhMuc.setText("");
            fillTable();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm Danh Mục Không Thành Công", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (showPasswordDialog()) {
            int dongDangChon = tblDanhMuc.getSelectedRow();
            if (dongDangChon != -1) {
                int MaDanhMuc = (int) tblDanhMuc.getValueAt(dongDangChon, 0);

                DanhMucDAO danhMucDao = new DanhMucDAO();
                int ketQua = danhMucDao.XoaDanhMuc(MaDanhMuc);

                if (ketQua == 1) {
                    JOptionPane.showMessageDialog(this, "Xoá Danh Mục Thành Công");
                    txtTenDanhMuc.setText("");
                    fillTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Xoá Danh Mục Không Thành Công", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng dữ liệu để xóa", "Error", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblDanhMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhMucMouseClicked
        // TODO add your handling code here:
        int dongDangChon = tblDanhMuc.getSelectedRow();

        String TenDanhMuc = tblDanhMuc.getValueAt(dongDangChon, 1).toString();
        txtTenDanhMuc.setText(TenDanhMuc);
    }//GEN-LAST:event_tblDanhMucMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int dongDangChon = tblDanhMuc.getSelectedRow();

        if (dongDangChon != -1) {
            String TenDanhMuc = txtTenDanhMuc.getText();
            int MaDanhMuc = (int) tblDanhMuc.getValueAt(dongDangChon, 0);
            if (TenDanhMuc.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không Được Để Trống Tên", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            DanhMucDAO danhMucDao = new DanhMucDAO();
            DanhMuc danhMuc = new DanhMuc(MaDanhMuc, TenDanhMuc);
            int ketQua = danhMucDao.SuaDanhMuc(danhMuc);

            if (ketQua == 1) {
                JOptionPane.showMessageDialog(this, "Sửa Danh Mục Thành Công");
                txtTenDanhMuc.setText("");
                fillTable();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa Danh Mục Không Thành Công", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng dữ liệu để sửa", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSTableMetro tblDanhMuc;
    private javax.swing.JTextField txtTenDanhMuc;
    // End of variables declaration//GEN-END:variables
}
