/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.ThongKeDAO;
import dto.DoanhThuChiTietDTO;
import dto.SanPhamBanChayDTO;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author admim
 */
public class QuanLyThongKeJpanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyThongKeJpanel
     */
    public QuanLyThongKeJpanel() {
        initComponents();
        tinhDoanhThu();
        tinhSoHoaDon();
        tinhSoSanPhamBanRa();
        tinhTopSanPhamBanChayTatCa();
        doanhThuChiTietHomNay();
    }
    
    public void tinhDoanhThu() {
        // Tổng tiền của tất cả đơn hàng có trạng thái Hoàn thành
        ThongKeDAO thongKeDAO = new ThongKeDAO();
        double doanhThu = thongKeDAO.tinhDoanhThu();
        jLabel2.setText(String.valueOf(doanhThu));
    }
    
    public void tinhSoHoaDon() {
        // Tổng đơn hàng có trạng thái Hoàn thành
        ThongKeDAO thongKeDAO = new ThongKeDAO();
        double soHoaDon = thongKeDAO.tinhSoHoaDon();
        jLabel5.setText(String.valueOf(soHoaDon));
    }
    
    public void tinhSoSanPhamBanRa() {
        ThongKeDAO thongKeDAO = new ThongKeDAO();
        double soSanPhamBanRa = thongKeDAO.tinhSoSanPhamBanRa();
        jLabel8.setText(String.valueOf(soSanPhamBanRa));
    }
    
    public void tinhTopSanPhamBanChayTatCa() {
        DefaultTableModel tableSanPham = (DefaultTableModel) this.rSTableMetro1.getModel();
        tableSanPham.setRowCount(0);
        
        ThongKeDAO thongKeDAO = new ThongKeDAO();
        List<SanPhamBanChayDTO> sanPhamLst = thongKeDAO.tinhTopSanPhamBanChayTatCa();
        
        for (SanPhamBanChayDTO sanPham : sanPhamLst) {
            tableSanPham.addRow(new Object[] {
                sanPham.getMaSP(),
                sanPham.getTenSP(),
                sanPham.getSoLuongBanRa(),
            });
        }
    }
    
    public void tinhTopSanPhamBanChayNgayNay() {
        DefaultTableModel tableSanPham = (DefaultTableModel) this.rSTableMetro1.getModel();
        tableSanPham.setRowCount(0);
        
        ThongKeDAO thongKeDAO = new ThongKeDAO();
        List<SanPhamBanChayDTO> sanPhamLst = thongKeDAO.tinhTopSanPhamBanChayNgayNay();
        
        for (SanPhamBanChayDTO sanPham : sanPhamLst) {
            tableSanPham.addRow(new Object[] {
                sanPham.getMaSP(),
                sanPham.getTenSP(),
                sanPham.getSoLuongBanRa(),
            });
        }
    }
   
    public void tinhTopSanPhamBanChayThangNay() {
        DefaultTableModel tableSanPham = (DefaultTableModel) this.rSTableMetro1.getModel();
        tableSanPham.setRowCount(0);
        
        ThongKeDAO thongKeDAO = new ThongKeDAO();
        List<SanPhamBanChayDTO> sanPhamLst = thongKeDAO.tinhTopSanPhamBanChayThangNay();
        
        for (SanPhamBanChayDTO sanPham : sanPhamLst) {
            tableSanPham.addRow(new Object[] {
                sanPham.getMaSP(),
                sanPham.getTenSP(),
                sanPham.getSoLuongBanRa(),
            });
        }
    }
    
    public void tinhTopSanPhamBanChayNamNay() {
        DefaultTableModel tableSanPham = (DefaultTableModel) this.rSTableMetro1.getModel();
        tableSanPham.setRowCount(0);
        
        ThongKeDAO thongKeDAO = new ThongKeDAO();
        List<SanPhamBanChayDTO> sanPhamLst = thongKeDAO.tinhTopSanPhamBanChayNamNay();
        
        for (SanPhamBanChayDTO sanPham : sanPhamLst) {
            tableSanPham.addRow(new Object[] {
                sanPham.getMaSP(),
                sanPham.getTenSP(),
                sanPham.getSoLuongBanRa(),
            });
        }
    }
    
    private void doanhThuChiTietHomNay(){
        DefaultTableModel model = (DefaultTableModel) tblChiTietDoanhThuHomNay.getModel();
        model.setRowCount(0);
        
        ThongKeDAO thongKeDAO = new ThongKeDAO();
        List<DoanhThuChiTietDTO> doanhThuLst = thongKeDAO.doanhThuChiTietHomNay();
        
        for (DoanhThuChiTietDTO doanhThuChiTietDTO : doanhThuLst) {
            model.addRow(new Object[]{
                doanhThuChiTietDTO.getMaSP(),
                doanhThuChiTietDTO.getTenSP(),
                doanhThuChiTietDTO.getTongSoLuongBanRa(),
                doanhThuChiTietDTO.getTongTienSanPhamBanRa()
            });
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxAndWhiskerRenderer1 = new org.jfree.chart.renderer.category.BoxAndWhiskerRenderer();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboLoc = new rojerusan.RSComboMetro();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojerusan.RSTableMetro();
        jLabel13 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblChiTietDoanhThuHomNay = new rojerusan.RSTableMetro();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1500, 1000));
        setMinimumSize(new java.awt.Dimension(1500, 1000));
        setPreferredSize(new java.awt.Dimension(1500, 1000));

        jPanel11.setBackground(new java.awt.Color(246, 225, 225));
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(128, 0, 0)));
        jPanel11.setPreferredSize(new java.awt.Dimension(1300, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-cart-128.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(128, 0, 0));
        jLabel2.setText("0 VND");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(128, 0, 0));
        jLabel3.setText("Doanh Thu");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(201, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)))
                .addGap(27, 27, 27))
        );

        jPanel12.setBackground(new java.awt.Color(246, 225, 225));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(128, 0, 0)));
        jPanel12.setPreferredSize(new java.awt.Dimension(1300, 300));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(128, 0, 0));
        jLabel4.setText("Số Hoá Đơn");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(128, 0, 0));
        jLabel5.setText("0");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/money-2-128.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(197, Short.MAX_VALUE))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5)))
                .addGap(27, 27, 27))
        );

        jPanel13.setBackground(new java.awt.Color(246, 225, 225));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(128, 0, 0)));
        jPanel13.setPreferredSize(new java.awt.Dimension(1300, 300));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/product-128.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(128, 0, 0));
        jLabel8.setText("0");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(128, 0, 0));
        jLabel9.setText("Số Sản Phẩm Bán Ra");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(39, Short.MAX_VALUE))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel8)))
                .addGap(27, 27, 27))
        );

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(128, 0, 0));
        jLabel10.setText("Lọc Theo:");

        cboLoc.setBackground(new java.awt.Color(246, 225, 225));
        cboLoc.setForeground(new java.awt.Color(128, 0, 0));
        cboLoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất Cả", "Ngày Này", "Tháng Này", "Năm Này" }));
        cboLoc.setColorArrow(new java.awt.Color(128, 0, 0));
        cboLoc.setColorBorde(new java.awt.Color(128, 0, 0));
        cboLoc.setColorFondo(new java.awt.Color(246, 225, 225));
        cboLoc.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cboLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLocActionPerformed(evt);
            }
        });

        jPanel14.setBackground(new java.awt.Color(246, 225, 225));
        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(128, 0, 0)));
        jPanel14.setPreferredSize(new java.awt.Dimension(1300, 300));

        jPanel15.setBackground(new java.awt.Color(246, 225, 225));
        jPanel15.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(128, 0, 0)));
        jPanel15.setPreferredSize(new java.awt.Dimension(1300, 300));

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng Bán Ra"
            }
        ));
        rSTableMetro1.setColorBackgoundHead(new java.awt.Color(128, 0, 0));
        rSTableMetro1.setColorBordeFilas(new java.awt.Color(128, 0, 0));
        rSTableMetro1.setColorBordeHead(new java.awt.Color(246, 225, 225));
        rSTableMetro1.setColorFilasBackgound1(new java.awt.Color(246, 225, 225));
        rSTableMetro1.setColorFilasBackgound2(new java.awt.Color(246, 225, 225));
        rSTableMetro1.setColorFilasForeground1(new java.awt.Color(128, 0, 0));
        rSTableMetro1.setColorFilasForeground2(new java.awt.Color(128, 0, 0));
        rSTableMetro1.setColorSelBackgound(new java.awt.Color(128, 0, 0));
        rSTableMetro1.setColorSelForeground(new java.awt.Color(246, 225, 225));
        rSTableMetro1.setFuenteHead(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jScrollPane3.setViewportView(rSTableMetro1);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(128, 0, 0));
        jLabel13.setText("Top 10 Sản Phẩm Bán Chạy");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(67, 67, 67))
            .addComponent(jScrollPane3)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3))
        );

        jPanel16.setBackground(new java.awt.Color(246, 225, 225));
        jPanel16.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(128, 0, 0)));
        jPanel16.setPreferredSize(new java.awt.Dimension(1300, 300));

        tblChiTietDoanhThuHomNay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng Bán Ra", "Tổng Tiền Bán Ra"
            }
        ));
        tblChiTietDoanhThuHomNay.setColorBackgoundHead(new java.awt.Color(128, 0, 0));
        tblChiTietDoanhThuHomNay.setColorBordeFilas(new java.awt.Color(128, 0, 0));
        tblChiTietDoanhThuHomNay.setColorBordeHead(new java.awt.Color(246, 225, 225));
        tblChiTietDoanhThuHomNay.setColorFilasBackgound1(new java.awt.Color(246, 225, 225));
        tblChiTietDoanhThuHomNay.setColorFilasBackgound2(new java.awt.Color(246, 225, 225));
        tblChiTietDoanhThuHomNay.setColorFilasForeground1(new java.awt.Color(128, 0, 0));
        tblChiTietDoanhThuHomNay.setColorFilasForeground2(new java.awt.Color(128, 0, 0));
        tblChiTietDoanhThuHomNay.setColorSelBackgound(new java.awt.Color(128, 0, 0));
        tblChiTietDoanhThuHomNay.setColorSelForeground(new java.awt.Color(246, 225, 225));
        tblChiTietDoanhThuHomNay.setFuenteHead(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jScrollPane4.setViewportView(tblChiTietDoanhThuHomNay);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(128, 0, 0));
        jLabel14.setText("Chi Tiết Doanh Thu Hôm Nay");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(115, 115, 115))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel10)
                        .addGap(50, 50, 50)
                        .addComponent(cboLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 1442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(36, 36, 36)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLocActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) cboLoc.getSelectedItem();

        if (selectedItem.equals("Tất Cả")) {
            tinhTopSanPhamBanChayTatCa();
        } else if (selectedItem.equals("Ngày Này")) {
            tinhTopSanPhamBanChayNgayNay();
        } else if (selectedItem.equals("Tháng Này")) {
            tinhTopSanPhamBanChayThangNay();
        } else if (selectedItem.equals("Năm Này")) {
            tinhTopSanPhamBanChayNamNay();
        }
    }//GEN-LAST:event_cboLocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jfree.chart.renderer.category.BoxAndWhiskerRenderer boxAndWhiskerRenderer1;
    private rojerusan.RSComboMetro cboLoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private rojerusan.RSTableMetro rSTableMetro1;
    private rojerusan.RSTableMetro tblChiTietDoanhThuHomNay;
    // End of variables declaration//GEN-END:variables
}
